vich_uploader:
    db_driver: orm

    mappings:
        event_image:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
